import { LevelData } from '../types';

export const LEVEL_1: LevelData = {
  id: 1,
  name: 'STAGE 1',
  subtitle: 'JUNGLE ISLAND',
  width: 3200,
  height: 288,
  theme: 'jungle',
  bgColor: '#0f172a',
  platforms: [
    // Starting ground
    { x: 0, y: 224, width: 380, height: 64 },
    // First high ledge
    { x: 120, y: 160, width: 140, height: 16, isOneWay: true },
    { x: 280, y: 120, width: 160, height: 16, isOneWay: true },

    // Bridge 1 (Exploding bridge!)
    { x: 380, y: 224, width: 160, height: 14, isBridge: true, fuseTimer: 2500 },
    // Water underneath bridge
    { x: 380, y: 248, width: 160, height: 40, isWater: true },

    // Mid ground after bridge 1
    { x: 540, y: 224, width: 320, height: 64 },
    { x: 620, y: 160, width: 180, height: 16, isOneWay: true },
    { x: 740, y: 100, width: 140, height: 16, isOneWay: true },

    // Water section with Scuba soldiers
    { x: 860, y: 236, width: 220, height: 52, isWater: true },
    // Stepping platforms over water
    { x: 900, y: 170, width: 60, height: 14, isOneWay: true },
    { x: 990, y: 150, width: 60, height: 14, isOneWay: true },

    // Second bridge
    { x: 1080, y: 224, width: 180, height: 14, isBridge: true, fuseTimer: 2000 },
    { x: 1080, y: 248, width: 180, height: 40, isWater: true },

    // Fort Approach Ground
    { x: 1260, y: 224, width: 420, height: 64 },
    { x: 1340, y: 160, width: 140, height: 16, isOneWay: true },
    { x: 1500, y: 120, width: 160, height: 16, isOneWay: true },
    { x: 1620, y: 80, width: 120, height: 16, isOneWay: true },

    // Trench water
    { x: 1680, y: 236, width: 140, height: 52, isWater: true },
    { x: 1710, y: 170, width: 80, height: 14, isOneWay: true },

    // Boss Arena Ground & High Platforms
    { x: 1820, y: 224, width: 800, height: 64 },
    { x: 1860, y: 160, width: 140, height: 14, isOneWay: true },
    { x: 2020, y: 120, width: 160, height: 14, isOneWay: true },
    { x: 2200, y: 160, width: 140, height: 14, isOneWay: true },
  ],
  initialEnemies: [
    // Pre-placed snipers & pillbox turrets
    {
      id: 101,
      type: 'sniper',
      x: 320,
      y: 96,
      vx: 0,
      vy: 0,
      width: 24,
      height: 24,
      health: 1,
      maxHealth: 1,
      direction: -1,
      shootCooldown: 1200,
      active: true,
      animFrame: 0,
    },
    {
      id: 102,
      type: 'turret',
      x: 640,
      y: 192,
      vx: 0,
      vy: 0,
      width: 32,
      height: 32,
      health: 8,
      maxHealth: 8,
      direction: -1,
      shootCooldown: 1800,
      active: true,
      animFrame: 0,
    },
    {
      id: 103,
      type: 'sniper',
      x: 780,
      y: 76,
      vx: 0,
      vy: 0,
      width: 24,
      height: 24,
      health: 1,
      maxHealth: 1,
      direction: -1,
      shootCooldown: 1500,
      active: true,
      animFrame: 0,
    },
    {
      id: 104,
      type: 'scuba',
      x: 940,
      y: 224,
      vx: 0,
      vy: 0,
      width: 24,
      height: 24,
      health: 2,
      maxHealth: 2,
      direction: -1,
      shootCooldown: 2200,
      submerged: true,
      submergeTimer: 1800,
      active: true,
      animFrame: 0,
    },
    {
      id: 105,
      type: 'turret',
      x: 1420,
      y: 192,
      vx: 0,
      vy: 0,
      width: 32,
      height: 32,
      health: 8,
      maxHealth: 8,
      direction: -1,
      shootCooldown: 1600,
      active: true,
      animFrame: 0,
    },
    {
      id: 106,
      type: 'sniper',
      x: 1660,
      y: 56,
      vx: 0,
      vy: 0,
      width: 24,
      height: 24,
      health: 1,
      maxHealth: 1,
      direction: -1,
      shootCooldown: 1400,
      active: true,
      animFrame: 0,
    },
    {
      id: 107,
      type: 'scuba',
      x: 1720,
      y: 224,
      vx: 0,
      vy: 0,
      width: 24,
      height: 24,
      health: 2,
      maxHealth: 2,
      direction: -1,
      shootCooldown: 2000,
      submerged: true,
      submergeTimer: 2000,
      active: true,
      animFrame: 0,
    },
    // Embedded Wall Sensor with Spread Gun
    {
      id: 108,
      type: 'wall_sensor',
      x: 600,
      y: 196,
      vx: 0,
      vy: 0,
      width: 20,
      height: 24,
      health: 4,
      maxHealth: 4,
      direction: -1,
      shootCooldown: 999999,
      dropWeapon: 'S',
      active: true,
      animFrame: 0,
    },
  ],
  enemySpawners: [
    // Dynamic runner waves that spawn as player advances
    {
      triggerX: 80,
      spawnX: 420,
      spawnY: 196,
      type: 'runner',
      interval: 2200,
      maxCount: 8,
      currentCount: 0,
      lastSpawn: 0,
    },
    {
      triggerX: 500,
      spawnX: 840,
      spawnY: 196,
      type: 'runner',
      interval: 2000,
      maxCount: 10,
      currentCount: 0,
      lastSpawn: 0,
    },
    {
      triggerX: 1200,
      spawnX: 1650,
      spawnY: 196,
      type: 'runner',
      interval: 1800,
      maxCount: 12,
      currentCount: 0,
      lastSpawn: 0,
    },
  ],
  capsules: [
    // Flying weapon capsules across the sky
    { triggerX: 100, weapon: 'M', spawned: false },
    { triggerX: 350, weapon: 'S', spawned: false }, // Iconic Spread Gun early on!
    { triggerX: 700, weapon: 'L', spawned: false },
    { triggerX: 1000, weapon: 'F', spawned: false },
    { triggerX: 1300, weapon: 'S', spawned: false },
    { triggerX: 1600, weapon: 'B', spawned: false }, // Barrier invulnerability
  ],
  boss: {
    type: 'fortress',
    name: 'GOMERAMOS DEFENSE GATE',
    x: 2360,
    y: 32,
    width: 140,
    height: 192,
    active: false,
    defeated: false,
    introDone: false,
    parts: [
      {
        id: 'radar',
        name: 'Sensor Array',
        x: 2380,
        y: 36,
        width: 32,
        height: 24,
        health: 12,
        maxHealth: 12,
        destroyed: false,
        shootCooldown: 2200,
      },
      {
        id: 'turret_top',
        name: 'Upper Laser Cannon',
        x: 2364,
        y: 80,
        width: 30,
        height: 24,
        health: 20,
        maxHealth: 20,
        destroyed: false,
        shootCooldown: 1600,
      },
      {
        id: 'turret_bottom',
        name: 'Lower Laser Cannon',
        x: 2364,
        y: 136,
        width: 30,
        height: 24,
        health: 20,
        maxHealth: 20,
        destroyed: false,
        shootCooldown: 1900,
      },
      {
        id: 'core',
        name: 'Fortress Energy Core',
        x: 2400,
        y: 108,
        width: 36,
        height: 36,
        health: 40,
        maxHealth: 40,
        destroyed: false,
        shootCooldown: 2500,
        isCore: true,
      },
    ],
  },
};

// ==========================================
// STAGE 2: WATERFALL CANYON
// ==========================================
export const LEVEL_2: LevelData = {
  id: 2,
  name: 'STAGE 2',
  subtitle: 'WATERFALL CANYON',
  width: 3200,
  height: 288,
  theme: 'waterfall',
  bgColor: '#0c1a2e',
  platforms: [
    // Starting cliff
    { x: 0, y: 224, width: 340, height: 64 },
    { x: 100, y: 160, width: 120, height: 16, isOneWay: true },
    { x: 220, y: 110, width: 140, height: 16, isOneWay: true },

    // Rushing river with rope bridge
    { x: 340, y: 224, width: 180, height: 14, isBridge: true, fuseTimer: 2500 },
    { x: 340, y: 246, width: 180, height: 42, isWater: true },

    // Middle canyon tiered rocks
    { x: 520, y: 224, width: 320, height: 64 },
    { x: 580, y: 160, width: 140, height: 16, isOneWay: true },
    { x: 700, y: 100, width: 150, height: 16, isOneWay: true },
    { x: 620, y: 60, width: 120, height: 16, isOneWay: true },

    // Churning waterfall river section with stepping crags
    { x: 840, y: 240, width: 260, height: 48, isWater: true },
    { x: 880, y: 170, width: 64, height: 14, isOneWay: true },
    { x: 970, y: 140, width: 64, height: 14, isOneWay: true },
    { x: 1050, y: 170, width: 64, height: 14, isOneWay: true },

    // High cliff ascent
    { x: 1100, y: 224, width: 380, height: 64 },
    { x: 1180, y: 160, width: 140, height: 16, isOneWay: true },
    { x: 1320, y: 110, width: 150, height: 16, isOneWay: true },
    { x: 1220, y: 70, width: 120, height: 16, isOneWay: true },

    // Second waterfall gorge
    { x: 1480, y: 224, width: 160, height: 14, isBridge: true, fuseTimer: 2000 },
    { x: 1480, y: 246, width: 160, height: 42, isWater: true },

    // Boss cavern approach
    { x: 1640, y: 224, width: 480, height: 64 },
    { x: 1720, y: 160, width: 140, height: 16, isOneWay: true },
    { x: 1880, y: 110, width: 150, height: 16, isOneWay: true },

    // Boss Arena (Bima Cyber Dragon)
    { x: 2120, y: 224, width: 800, height: 64 },
    { x: 2160, y: 160, width: 130, height: 14, isOneWay: true },
    { x: 2320, y: 120, width: 150, height: 14, isOneWay: true },
    { x: 2500, y: 160, width: 130, height: 14, isOneWay: true },
  ],
  initialEnemies: [
    {
      id: 201,
      type: 'sniper',
      x: 280,
      y: 86,
      vx: 0,
      vy: 0,
      width: 24,
      height: 24,
      health: 2,
      maxHealth: 2,
      direction: -1,
      shootCooldown: 1300,
      active: true,
      animFrame: 0,
    },
    {
      id: 202,
      type: 'turret',
      x: 640,
      y: 192,
      vx: 0,
      vy: 0,
      width: 32,
      height: 32,
      health: 8,
      maxHealth: 8,
      direction: -1,
      shootCooldown: 1600,
      active: true,
      animFrame: 0,
    },
    {
      id: 203,
      type: 'scuba',
      x: 920,
      y: 228,
      vx: 0,
      vy: 0,
      width: 24,
      height: 24,
      health: 2,
      maxHealth: 2,
      direction: -1,
      shootCooldown: 2000,
      submerged: true,
      submergeTimer: 1800,
      active: true,
      animFrame: 0,
    },
    {
      id: 204,
      type: 'wall_sensor',
      x: 600,
      y: 196,
      vx: 0,
      vy: 0,
      width: 20,
      height: 24,
      health: 4,
      maxHealth: 4,
      direction: -1,
      shootCooldown: 999999,
      dropWeapon: 'S',
      active: true,
      animFrame: 0,
    },
    {
      id: 205,
      type: 'sniper',
      x: 1260,
      y: 46,
      vx: 0,
      vy: 0,
      width: 24,
      height: 24,
      health: 2,
      maxHealth: 2,
      direction: -1,
      shootCooldown: 1400,
      active: true,
      animFrame: 0,
    },
    {
      id: 206,
      type: 'turret',
      x: 1380,
      y: 192,
      vx: 0,
      vy: 0,
      width: 32,
      height: 32,
      health: 9,
      maxHealth: 9,
      direction: -1,
      shootCooldown: 1500,
      active: true,
      animFrame: 0,
    },
    {
      id: 207,
      type: 'wall_sensor',
      x: 1200,
      y: 196,
      vx: 0,
      vy: 0,
      width: 20,
      height: 24,
      health: 5,
      maxHealth: 5,
      direction: -1,
      shootCooldown: 999999,
      dropWeapon: 'L',
      active: true,
      animFrame: 0,
    },
  ],
  enemySpawners: [
    {
      triggerX: 100,
      spawnX: 450,
      spawnY: 196,
      type: 'runner',
      interval: 2000,
      maxCount: 9,
      currentCount: 0,
      lastSpawn: 0,
    },
    {
      triggerX: 600,
      spawnX: 1050,
      spawnY: 196,
      type: 'alien_crawler',
      interval: 2200,
      maxCount: 8,
      currentCount: 0,
      lastSpawn: 0,
    },
    {
      triggerX: 1200,
      spawnX: 1700,
      spawnY: 196,
      type: 'runner',
      interval: 1800,
      maxCount: 11,
      currentCount: 0,
      lastSpawn: 0,
    },
  ],
  capsules: [
    { triggerX: 120, weapon: 'M', spawned: false },
    { triggerX: 450, weapon: 'S', spawned: false },
    { triggerX: 900, weapon: 'F', spawned: false },
    { triggerX: 1350, weapon: 'L', spawned: false },
    { triggerX: 1650, weapon: 'B', spawned: false },
  ],
  boss: {
    type: 'bima_dragon',
    name: 'CYBER DRAGON GUARDIAN BIMA',
    x: 2360,
    y: 36,
    width: 140,
    height: 188,
    active: false,
    defeated: false,
    introDone: false,
    parts: [
      {
        id: 'dragon_head',
        name: 'Dragon Cyber Horns',
        x: 2374,
        y: 40,
        width: 38,
        height: 34,
        health: 24,
        maxHealth: 24,
        destroyed: false,
        shootCooldown: 2000,
      },
      {
        id: 'left_launcher',
        name: 'Upper Flak Launcher',
        x: 2360,
        y: 84,
        width: 32,
        height: 26,
        health: 20,
        maxHealth: 20,
        destroyed: false,
        shootCooldown: 2400,
      },
      {
        id: 'right_launcher',
        name: 'Lower Laser Pod',
        x: 2360,
        y: 136,
        width: 32,
        height: 26,
        health: 20,
        maxHealth: 20,
        destroyed: false,
        shootCooldown: 2800,
      },
      {
        id: 'core',
        name: 'Dragon Energy Heart',
        x: 2402,
        y: 104,
        width: 38,
        height: 38,
        health: 48,
        maxHealth: 48,
        destroyed: false,
        shootCooldown: 2200,
        isCore: true,
      },
    ],
  },
};

// ==========================================
// STAGE 3: SNOW BASE FORTRESS
// ==========================================
export const LEVEL_3: LevelData = {
  id: 3,
  name: 'STAGE 3',
  subtitle: 'SNOW BASE FORTRESS',
  width: 3200,
  height: 288,
  theme: 'snow',
  bgColor: '#08111e',
  platforms: [
    // Starting snow ground
    { x: 0, y: 224, width: 360, height: 64 },
    { x: 120, y: 160, width: 140, height: 16, isOneWay: true },
    { x: 260, y: 110, width: 150, height: 16, isOneWay: true },

    // Steel Bunker Bridge over frozen crevasse
    { x: 360, y: 224, width: 180, height: 14, isBridge: true, fuseTimer: 2400 },
    { x: 360, y: 248, width: 180, height: 40, isWater: true }, // Frozen trench

    // Catwalk base
    { x: 540, y: 224, width: 360, height: 64 },
    { x: 620, y: 160, width: 150, height: 16, isOneWay: true },
    { x: 740, y: 100, width: 140, height: 16, isOneWay: true },
    { x: 660, y: 60, width: 120, height: 16, isOneWay: true },

    // Frozen ice lake gap with elevated iron girders
    { x: 900, y: 240, width: 240, height: 48, isWater: true },
    { x: 930, y: 170, width: 70, height: 14, isOneWay: true },
    { x: 1020, y: 130, width: 70, height: 14, isOneWay: true },

    // Military Base catwalks
    { x: 1140, y: 224, width: 420, height: 64 },
    { x: 1220, y: 160, width: 150, height: 16, isOneWay: true },
    { x: 1380, y: 110, width: 150, height: 16, isOneWay: true },

    // Fort defense trench
    { x: 1560, y: 224, width: 180, height: 14, isBridge: true, fuseTimer: 2000 },
    { x: 1560, y: 248, width: 180, height: 40, isWater: true },

    // Boss Arena (Big Fuzz Siege Mech Tank)
    { x: 1740, y: 224, width: 880, height: 64 },
    { x: 1800, y: 160, width: 140, height: 14, isOneWay: true },
    { x: 1960, y: 120, width: 160, height: 14, isOneWay: true },
    { x: 2140, y: 160, width: 140, height: 14, isOneWay: true },
  ],
  initialEnemies: [
    {
      id: 301,
      type: 'sniper',
      x: 300,
      y: 86,
      vx: 0,
      vy: 0,
      width: 24,
      height: 24,
      health: 2,
      maxHealth: 2,
      direction: -1,
      shootCooldown: 1200,
      active: true,
      animFrame: 0,
    },
    {
      id: 302,
      type: 'turret',
      x: 680,
      y: 192,
      vx: 0,
      vy: 0,
      width: 32,
      height: 32,
      health: 10,
      maxHealth: 10,
      direction: -1,
      shootCooldown: 1500,
      active: true,
      animFrame: 0,
    },
    {
      id: 303,
      type: 'wall_sensor',
      x: 600,
      y: 196,
      vx: 0,
      vy: 0,
      width: 20,
      height: 24,
      health: 5,
      maxHealth: 5,
      direction: -1,
      shootCooldown: 999999,
      dropWeapon: 'M',
      active: true,
      animFrame: 0,
    },
    {
      id: 304,
      type: 'sniper',
      x: 1300,
      y: 86,
      vx: 0,
      vy: 0,
      width: 24,
      height: 24,
      health: 2,
      maxHealth: 2,
      direction: -1,
      shootCooldown: 1300,
      active: true,
      animFrame: 0,
    },
    {
      id: 305,
      type: 'turret',
      x: 1440,
      y: 192,
      vx: 0,
      vy: 0,
      width: 32,
      height: 32,
      health: 10,
      maxHealth: 10,
      direction: -1,
      shootCooldown: 1400,
      active: true,
      animFrame: 0,
    },
    {
      id: 306,
      type: 'wall_sensor',
      x: 1240,
      y: 196,
      vx: 0,
      vy: 0,
      width: 20,
      height: 24,
      health: 5,
      maxHealth: 5,
      direction: -1,
      shootCooldown: 999999,
      dropWeapon: 'F',
      active: true,
      animFrame: 0,
    },
  ],
  enemySpawners: [
    {
      triggerX: 80,
      spawnX: 420,
      spawnY: 196,
      type: 'runner',
      interval: 1800,
      maxCount: 10,
      currentCount: 0,
      lastSpawn: 0,
    },
    {
      triggerX: 550,
      spawnX: 950,
      spawnY: 196,
      type: 'runner',
      interval: 1700,
      maxCount: 10,
      currentCount: 0,
      lastSpawn: 0,
    },
    {
      triggerX: 1150,
      spawnX: 1650,
      spawnY: 196,
      type: 'runner',
      interval: 1600,
      maxCount: 12,
      currentCount: 0,
      lastSpawn: 0,
    },
  ],
  capsules: [
    { triggerX: 120, weapon: 'S', spawned: false },
    { triggerX: 480, weapon: 'L', spawned: false },
    { triggerX: 880, weapon: 'B', spawned: false },
    { triggerX: 1280, weapon: 'S', spawned: false },
    { triggerX: 1600, weapon: 'BOMB', spawned: false },
  ],
  boss: {
    type: 'armored_tank',
    name: 'SIEGE TANK BIG FUZZ D-34',
    x: 2350,
    y: 60,
    width: 150,
    height: 164,
    active: false,
    defeated: false,
    introDone: false,
    parts: [
      {
        id: 'tank_turret',
        name: 'Dual Howitzer Cannon',
        x: 2360,
        y: 70,
        width: 38,
        height: 28,
        health: 26,
        maxHealth: 26,
        destroyed: false,
        shootCooldown: 2200,
      },
      {
        id: 'tank_mortar',
        name: 'Flak Mortar Bay',
        x: 2364,
        y: 120,
        width: 32,
        height: 24,
        health: 22,
        maxHealth: 22,
        destroyed: false,
        shootCooldown: 2600,
      },
      {
        id: 'tread_guard',
        name: 'Steel Treads Armor',
        x: 2356,
        y: 162,
        width: 70,
        height: 30,
        health: 28,
        maxHealth: 28,
        destroyed: false,
        shootCooldown: 3200,
      },
      {
        id: 'core',
        name: 'Diesel Boiler Core',
        x: 2404,
        y: 104,
        width: 40,
        height: 40,
        health: 54,
        maxHealth: 54,
        destroyed: false,
        shootCooldown: 2000,
        isCore: true,
      },
    ],
  },
};

// ==========================================
// STAGE 4: ALIEN HIVE & EMPEROR JAVA
// ==========================================
export const LEVEL_4: LevelData = {
  id: 4,
  name: 'STAGE 4',
  subtitle: 'ALIEN HIVE & EMPEROR JAVA',
  width: 3200,
  height: 288,
  theme: 'alien',
  bgColor: '#16021f',
  platforms: [
    // Fleshy starting platform
    { x: 0, y: 224, width: 380, height: 64 },
    { x: 140, y: 150, width: 140, height: 16, isOneWay: true },
    { x: 300, y: 110, width: 160, height: 16, isOneWay: true },

    // Biomechanical spine bridge
    { x: 380, y: 224, width: 180, height: 14, isBridge: true, fuseTimer: 2200 },
    { x: 380, y: 248, width: 180, height: 40, isWater: true }, // Acid pool

    // Central bio-nest
    { x: 560, y: 224, width: 380, height: 64 },
    { x: 640, y: 150, width: 140, height: 16, isOneWay: true },
    { x: 800, y: 90, width: 160, height: 16, isOneWay: true },
    { x: 700, y: 55, width: 120, height: 16, isOneWay: true },

    // Deep Acid Lake with living bone columns
    { x: 940, y: 242, width: 260, height: 46, isWater: true },
    { x: 980, y: 160, width: 70, height: 14, isOneWay: true },
    { x: 1080, y: 120, width: 70, height: 14, isOneWay: true },

    // Hive heart interior
    { x: 1200, y: 224, width: 420, height: 64 },
    { x: 1280, y: 150, width: 150, height: 16, isOneWay: true },
    { x: 1440, y: 110, width: 150, height: 16, isOneWay: true },

    // Pre-boss bridge
    { x: 1620, y: 224, width: 180, height: 14, isBridge: true, fuseTimer: 2000 },
    { x: 1620, y: 248, width: 180, height: 40, isWater: true },

    // Final Emperor Java Arena
    { x: 1800, y: 224, width: 840, height: 64 },
    { x: 1860, y: 150, width: 130, height: 14, isOneWay: true },
    { x: 2020, y: 110, width: 150, height: 14, isOneWay: true },
    { x: 2200, y: 150, width: 130, height: 14, isOneWay: true },
  ],
  initialEnemies: [
    {
      id: 401,
      type: 'alien_crawler',
      x: 340,
      y: 200,
      vx: -1.2,
      vy: 0,
      width: 20,
      height: 20,
      health: 3,
      maxHealth: 3,
      direction: -1,
      shootCooldown: 999999,
      active: true,
      animFrame: 0,
    },
    {
      id: 402,
      type: 'sniper',
      x: 760,
      y: 66,
      vx: 0,
      vy: 0,
      width: 24,
      height: 24,
      health: 3,
      maxHealth: 3,
      direction: -1,
      shootCooldown: 1100,
      active: true,
      animFrame: 0,
    },
    {
      id: 403,
      type: 'turret',
      x: 880,
      y: 192,
      vx: 0,
      vy: 0,
      width: 32,
      height: 32,
      health: 12,
      maxHealth: 12,
      direction: -1,
      shootCooldown: 1400,
      active: true,
      animFrame: 0,
    },
    {
      id: 404,
      type: 'wall_sensor',
      x: 620,
      y: 196,
      vx: 0,
      vy: 0,
      width: 20,
      height: 24,
      health: 5,
      maxHealth: 5,
      direction: -1,
      shootCooldown: 999999,
      dropWeapon: 'S',
      active: true,
      animFrame: 0,
    },
    {
      id: 405,
      type: 'sniper',
      x: 1360,
      y: 86,
      vx: 0,
      vy: 0,
      width: 24,
      height: 24,
      health: 3,
      maxHealth: 3,
      direction: -1,
      shootCooldown: 1100,
      active: true,
      animFrame: 0,
    },
    {
      id: 406,
      type: 'wall_sensor',
      x: 1240,
      y: 196,
      vx: 0,
      vy: 0,
      width: 20,
      height: 24,
      health: 6,
      maxHealth: 6,
      direction: -1,
      shootCooldown: 999999,
      dropWeapon: 'B',
      active: true,
      animFrame: 0,
    },
  ],
  enemySpawners: [
    {
      triggerX: 100,
      spawnX: 460,
      spawnY: 196,
      type: 'alien_crawler',
      interval: 1500,
      maxCount: 14,
      currentCount: 0,
      lastSpawn: 0,
    },
    {
      triggerX: 600,
      spawnX: 1100,
      spawnY: 196,
      type: 'alien_crawler',
      interval: 1500,
      maxCount: 14,
      currentCount: 0,
      lastSpawn: 0,
    },
    {
      triggerX: 1180,
      spawnX: 1720,
      spawnY: 196,
      type: 'runner',
      interval: 1500,
      maxCount: 14,
      currentCount: 0,
      lastSpawn: 0,
    },
  ],
  capsules: [
    { triggerX: 120, weapon: 'S', spawned: false },
    { triggerX: 460, weapon: 'L', spawned: false },
    { triggerX: 860, weapon: 'B', spawned: false },
    { triggerX: 1260, weapon: 'S', spawned: false },
    { triggerX: 1550, weapon: 'BOMB', spawned: false },
  ],
  boss: {
    type: 'emperor_java',
    name: 'SHADOW BEAST EMPEROR JAVA',
    x: 2340,
    y: 36,
    width: 150,
    height: 188,
    active: false,
    defeated: false,
    introDone: false,
    parts: [
      {
        id: 'java_skull',
        name: 'Emperor Java Skull',
        x: 2360,
        y: 40,
        width: 44,
        height: 44,
        health: 32,
        maxHealth: 32,
        destroyed: false,
        shootCooldown: 2000,
      },
      {
        id: 'left_tentacle',
        name: 'Upper Venom Tentacle',
        x: 2348,
        y: 92,
        width: 30,
        height: 28,
        health: 22,
        maxHealth: 22,
        destroyed: false,
        shootCooldown: 2400,
      },
      {
        id: 'right_tentacle',
        name: 'Lower Acid Tentacle',
        x: 2348,
        y: 136,
        width: 30,
        height: 28,
        health: 22,
        maxHealth: 22,
        destroyed: false,
        shootCooldown: 2700,
      },
      {
        id: 'core',
        name: 'Xenomorph Gowa Heart',
        x: 2404,
        y: 104,
        width: 44,
        height: 44,
        health: 64,
        maxHealth: 64,
        destroyed: false,
        shootCooldown: 1800,
        isCore: true,
      },
    ],
  },
};

export const ALL_LEVELS: LevelData[] = [LEVEL_1, LEVEL_2, LEVEL_3, LEVEL_4];
